machine:
  pre:
    - sudo apt-get update; USE_PRECOMPILE=true sudo -E circleci-install php 7.3.0

  php:
    version: 7.3.0

dependencies:
  override:
    - composer install --no-interaction
test:
  pre:
    - "./vendor/laravel/dusk/bin/chromedriver-linux":
        background: true
    - cp .env.example .env
    - "php artisan serve":
        background: true

  override:
    - php artisan dusk